### ISSUE TITLE
Trouble changing team name

### ISSUE THREAD

**Issue by cstevens780** [110yards/fantasy#11]
Receive error code 500 when changing team name. These are the steps leading to the error:
1. “My team” tab
2. Select edit pencil icon
3. Alter name
4. Select save
5. Error 500 shows and no changes are saved.

A work around is to change your display name in “My Profile” instead but I assume that will change all team names. Error noted on Android and Apple IOS.

**Comment by mdryden** [comment]
Thanks for the report, I noticed this one as well; it's on my list to fix in the next release.

**Comment by mdryden** [comment]
This should be fixed now, but only for new leagues.  This was a bug that affected any league which had done a draft.  It's fixed now, but since no one can draft in live yet, I didn't create a patch for existing leagues.  It should work for leagues in live once drafting is enabled (soon!), and for any league in test that you create and draft with going forward.
