### ISSUE TITLE
Drafting a Kicker before any RB/WR puts the Kicker in OFlex1 spot

### ISSUE THREAD

**Issue by ryankoop42** [110yards/fantasy#158]
When the league is configured to have an offensive flex spot - drafting a kicker before drafting any RBs or WRs puts the Kicker in the OFlex1 spot instead of the K1 spot.

When this happens, you are unable to properly finish the draft because the K1 slot is empty but you can't add a kicker since there's a max of 1 via the roster rules and you already have the kicker in the Flex spot

**Comment by mdryden** [comment]
Oh crap, that's a bad one.  Were you guys able to work around it?  I will work on a fix for that.

**Comment by mdryden** [comment]
Hopefully it's not too late to help you guys - if you haven't finished your draft yet, I've fixed this bug. The commissioner can undo some picks in order to re-apply picks and it should work correctly now.  When you add a player now, it will find positions in this order:

Natural positions > Offensive or Defensive Flex > Flex > Bench

**Comment by ryankoop42** [comment]
No worries, it was just a test draft I was doing to test out your site and see what kind of features were all available. Our actual draft isn't until next week. So no harm, no foul on our end! Appreciate you getting this fixed up so quickly! Overall the site looks and works great!
