### ISSUE TITLE
Generating league schedule

### ISSUE THREAD

**Issue by DaCommish** [110yards/fantasy#164]
I got error message when trying to generate a league schedule. 'Request failed with status code 500'

**Comment by mdryden** [comment]
I can see the error you are getting, it says that you have somehow managed to get 10 teams in the league?  I'm not sure how that happened, the site should have prevented that.  If you don't have 10 teams, let me know and I can figure out what went wrong.  If you do have 10 then I'm sorry to say that the maximum is 8.

**Comment by DaCommish** [comment]
Oh no! Yes we have 10 teams. Last year we used the official CFL fantasy league but didn't like the setup. I guess we'll have to use it again this year.

**Comment by mdryden** [comment]
If you're willing to wait a few days, I can take a look at what it would take to support 10 rosters.  In theory, I think the only limitation is that I didn't implement a schedule generator for that many teams because I thought I had restricted it to 8 teams max but apparently I missed something.

I can take a look at this one today/tonight and see what's required; if it's just the schedule, I should be able to implement that pretty quickly.

That said I do think you may have some competitive balance issues with 10 teams, as you're going to have teams who can't find a starting RB or QB, if you've configured those positions.

**Comment by DaCommish** [comment]
That's would be great! As long as we have time to draft before the season starts we can wait.

**Comment by mdryden** [comment]
Ok, I'll take a look and keep you posted here.

**Comment by mdryden** [comment]
This should work for you now - I built the scheduler for 10 teams and it seems to work ok.  Would you mind keeping in touch throughout the season and letting me know how it goes?  You can email me at pudds55 (at) gmail.com.

In addition to any issues you might right into, I'm curious to see how your season goes.  I always figured 8 players was the logical limit, with only 9 teams to choose starts from, but I'd like to hear how your experience is.  I fixed the limit for the site now to cap a league at 10 players, but if you guys find the game frustrating with 10 teams and decide not to come back, I might drop the limit to 8.

**Comment by DaCommish** [comment]
We're starting our playoffs this week. Why does the schedule say teams are TBD?
