### ISSUE TITLE
Injury status 

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#196]
It sure if this is a 110 yards issue or cfl API issue but Wes Hills has the injury symbol even though the last transaction log for him shows him being move from IR to active. 
 
Does it just take a while to update ?

**Comment by mdryden** [comment]
It does.

The CFL's API doesn't have any injury information, so I have to go to the individual team pages in order to get the injury status for players.  Unfortunately, I don't think all teams update their roster page very regularly, and it's often delayed.  Burnham, for instance, didn't show up on IR until 2 days after the article was published about his broken ribs.

Inconsistencies like this is unfortunately why the IR reserve positions aren't strict.  Some day I might look into using the transaction list instead (or in cooperation).
