### ISSUE TITLE
QB failed bid 

### ISSUE THREAD

**Issue by annamc604** [110yards/fantasy#201]
**Describe the bug**
I believe three teams bid for QB Trevor Harris and no one ended up with a successful bid.  In my waiver bid it noted that it failed due to outbud but the player was later acquired free during free agent.  I had an empty slot in my QB and the other QB was in a bye slot.

** 4XVWS3uyiwxXU4BAg0S7 *
Please include your league id if applicable.

**Roster name**
tlhIngan maH

**Screenshots**

**Device information** mobile device 
![Screenshot_20220712-203522_Samsung Internet](https://user-images.githubusercontent.com/109194934/178645161-b29ef8f7-1a22-4c79-9be5-bddb97195c3a.jpg)

Please indicate if you are using a mobile device or desktop, and the browser you are using, if applicable.

**Comment by mdryden** [comment]
Sorry for this.  From what you're describing, it sounds like someone in your league made a bid which couldn't be processed because they would have had an invalid roster, but your bid had already been removed since you were outbid.  

If this is indeed the case, then I agree that it's a bug and I will review the waiver process and get this fixed.

I think you'll have to work it out with your league to change the result though.
