### ISSUE TITLE
Waivers just ran early

### ISSUE THREAD

**Issue by Flaccoseagulls** [110yards/fantasy#238]
Hey There,

Looks like waivers ran right now vs Thursday morning like they were communicated in your post today.

**Comment by mdryden** [comment]
Yes I'm sorry for that (and for not answering early, I haven't been on top of the issues as much as discord).

I forgot to turn the waivers job off to delay it a day and I didn't notice until waivers had been unlocked for several hours.  After some consideration I felt it was most fair to leave it as-is, since players were added without waiver requests.

Waivers should work correctly going forward.
