### ISSUE TITLE
Schedule won't show winners

### ISSUE THREAD

**Issue by ShawnBongo** [110yards/fantasy#252]
I have a league set up and have had several GM's in my league reach out to me. They've been asking how to tell which team won in the head to head game from previous week? It doesn't show up in either of the standings or in the schedule. Could you please enlighten me on how to fix this issue?  Thanks

**Comment by mdryden** [comment]
Sorry for the issue Shawn.  I will take a look at this ASAP but I can't promise I'll get to it before Monday evening because I'm away this weekend.

I am able to go back and retroactively calculate results for a league so I can go back and make sure that the results are correct for all weeks so far on your league.

**Comment by ShawnBongo** [comment]
Thanks for getting back to me, I understand your busy and appreciate you
looking into this for us.

Thanks again,

Shawn Bonogofski

**Comment by ShawnBongo** [comment]
Good evening, so I'm not sure if you've ever had a chance to look into this
issue for me but my league standings still doesn't show who won on a week
to week basis. We can see who has won while games are being played but when
the week is finalized everything disappears. I'll attach a couple of
screenshots taken to show you the current issue. Thank you for your time
and giving us this fantasy football opportunity, I've been waiting a few
years to find something like this since fantaseh closed up shop.

Shawn Bonogofski
Bongo Built Construction Ltd.
306-361-8974
