### ISSUE TITLE
Players with no stats or team have points

### ISSUE THREAD

**Issue by kamikazecanuck** [110yards/fantasy#40]
I'm sure this has more to do with the CFL database/website but there's several players that have gotten points on 110yards.ca even though they have no team attached to them and no stats on CFL.ca. 
For example Obum GWACHUM officially on BC roster. Has 11 points in 110yards but no stats whatsoever on CFL.ca

Mike Jones is another.  (The DB).  There's 2 Mike Jones apparently.

**Comment by mdryden** [comment]
Yea something weird going on here.

At first glance, I'd say the issue here is that he wasn't in the CFL API before the game started; fortunately that was something I anticipated, so he was created when he showed up in the boxscore.  He definitely had stats in the game (https://www.cfl.ca/games/6135/bc-lions-vs-saskatchewan-roughriders/#boxscore) so that part is correct.

It's a bit odd that he isn't showing up on the BC roster though - I suspect this is similar to the Quan Bray issue we discovered early in the season - he's probably missing that key ID, and in this case he's probably missing an entry in the CFL's api as well (likely why he has no stats on the CFL website).

Fingers crossed, I'm thinking this will resolve itself when the CFL fixes their data, but I'll monitor it.

**Comment by kamikazecanuck** [comment]
Yes, at least his points came through automatically.

**Comment by DamonB88** [comment]
Curious where this is at. Particularly for Obum Gwachum. I think the issue might be with his last name. The BC lions depth chart for week 2, his last name is spelt Gwacham, but on CFl stats it is Gwachum. Not sure if this could be part of the issue or not, jsut something i noticed. As long as his stats keep showing up for my team I'm happy! Even if the website says he's a free agent!

Also, no idea what it means but on the BC Lions depth chart, he is the defensive end but his spot is labeled "QK", but on the roster page it's defensive lineman. Another weird quirk, no idea if it matters.

**Comment by kamikazecanuck** [comment]
Ya I picked him up too. As long as he gets his points..

**Comment by mdryden** [comment]
The name mismatch here is probably why he doesn't have a team, thanks for pointing it out.  The site uses last names to match up players that are missing their id on the official roster.

I should be able to manually fix Gwacham tomorrow.

**Comment by mdryden** [comment]
This one is going to be a bit tricky.

Basically, there are 3 errors in the CFL's data:

1) The BC Roster entry for Gwacham has no cfl ID or stats inc ID - I use these two numbers to match player data between the roster pages and the game data.

2) The CFL game data has the wrong last name for him.  I use the last name as a fix for problem number one, but since his name is wrong, that doesn't work either.

I've manually fixed his data, but chances are the next player update (every 3 hours) is going to decide that he's not on a team anymore since he's missing his IDs, which means he'll get set back to Free Agent.

He should still get stat updates, as he appears to be in the game data and those IDs should continue to work. But until the CFL fixes his data his team, opponent and possibly also his injury status is going to appear wrong.

I need to think on this one for a bit and see if I can come up with a workaround.

**Comment by mdryden** [comment]
https://github.com/mdryden/110yards-api/issues/88

**Comment by kamikazecanuck** [comment]
Ok sounds like it’s safe to keep him because he’ll still get his points though.

**Comment by mdryden** [comment]
Should be.  I hope.  I can't see why it wouldn't work, but my fingers are still crossed.

**Comment by Casper926** [comment]
Hey there - any new updates on this one?  Temporary issue and he is safe to keep or likely someone that might be unrosterable?

**Comment by mdryden** [comment]
I can't say with certainty, but my experience is that once the CFL assigns a player an id, its set forever.  That suggest to me that his name will get fixed and his stats will continue to work but it's really just an educated guess.
