### ISSUE TITLE
Player points not showing up in player tab

### ISSUE THREAD

**Issue by cstevens780** [110yards/fantasy#51]
When I go to the player tab it seems frequently that the points/yardage doesn’t upload so that everyone has zero stats except for games played. Is there a work around to get the stats to force load?

**Comment by mdryden** [comment]
Do you mean the player list page (search)?

If so, there's kind of a trick to it, which I should probably work on improving.  When looking at all players, you'll only see the GP, Rk, Points and Avg columns.  That's because with the full list of players, there are so many stat columns that I felt it would be overwhelming to display.

If you filter by position, the site will show you relevant stats for that position.  For example, click the RB button, and you should see the Rushing and Receiving columns appear.

**Comment by cstevens780** [comment]
The problem seems to be there are no numbers for the stats or point accumulation it shows zeros across the board. 

![7D258E77-0D1A-4F88-A7B5-7865A4A59D1E](https://user-images.githubusercontent.com/86929798/129574139-b1b9f563-2baf-4b49-8a35-f23eea9a95cb.png)
![BFFAE158-83DB-41E9-9630-08AB0CBFD6BE](https://user-images.githubusercontent.com/86929798/129574145-f7d17c9f-c4be-48fe-95b2-eb00aff45220.png)

**Comment by mdryden** [comment]
Oh crap, what the heck.

Ok, yes I'm seeing this too.  Something is wrong, I will fix ASAP.

**Comment by davidkinetisense** [comment]
Also people that are not on teams are being displayed in the players list.

**Comment by mdryden** [comment]
Players not on teams (Free agents) showing in the list is normal, I haven't filtered them out.  That's probably something I should consider, though currently there a couple of minor CFL data problems, like the one with Gwacham, making legit players show up as free agents, so I have to fix that bug first.

**Comment by mdryden** [comment]
This is fixed now.
